### ISSUE TITLE
Naming a data variable `arr` screws up rendering

### ISSUE THREAD

**Issue by wolframkriesing** [Usbac/tundra#1]
Thanks for the simple tool, I was looking for something like this.
I tried to render using `tundra.getRender('index.html', {arr: [1,2,3]});` and it rendered the template wrong.
I believe it is because of https://github.com/Usbac/tundra/blob/master/src/tundra.js#L7 which is used to collect all the parts in the code further down. Maybe using a Symbol could fix that.

**Comment by Usbac** [comment]
Hi @wolframkriesing! I'm really glad you liked Tundra, and also thank you so much for pointing out that bug, it has been fixed 7927561 :)

Regards!

**Comment by wolframkriesing** [comment]
Hi @Usbac cool, awesome speed in fixing it.

Did you consider `Symbol` for solving the uniqueness?
> Every symbol value returned from Symbol() is unique.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol

Since you have an ES6+ code base anyways, using Symbol should be no issue, right? Or are there other considerations against it?

**Comment by Usbac** [comment]
@wolframkriesing I was aware of `Symbol`, but I went for a more traditional solution, appending a random alphanumeric token to the variable name :)

If I'm not wrong, a Symbol cannot be used as the direct name of a variable since they cannot be implicitly cast to string.
