### ISSUE TITLE
Block throws when there is not at least one newline in it

### ISSUE THREAD

**Issue by wolframkriesing** [Usbac/tundra#2]
```
<body class="page-{[ block pagename ]}{[ endblock ]}">
```

throws the error

```
 UnhandledPromiseRejectionWarning: SyntaxError: Invalid regular expression: /(?<!~)(\{\[)( ?){1,}block( ?){1,}pagename ]}{[ endblock( ?){1,}(\]\})([\s\S]*?)(\{\[)( ?){1,}endblock( ?){1,}(\]\})/: Unmatched ')'
    at new RegExp (<anonymous>)
    at getBlock (/app/node_modules/tundrajs/src/tundra.js:289:23)
    at /app/node_modules/tundrajs/src/tundra.js:274:16
```

My current work around is to write the following, which works but is kinda ugly
```
<body class="page-{[ block pagename ]}
{[ endblock ]}">
```

**Comment by Usbac** [comment]
Hello @wolframkriesing, could you give a more complete example? Like a snippet of the child and the parent view if it's possible. Thanks.

Also I don't know if this complies with what you wanna get, but as an alternative, if you want to get the pagename block you can do the following:

parent:
```html
{[ block pagename ]}home{[ endblock ]}
```

child:
```html
<body class="page-{[ parent pagename ]}">
```

**Comment by wolframkriesing** [comment]
Hi @Usbac sorry, didnt see that earlier.
You can see me using it here 
https://github.com/wolframkriesing/site-stitcher/blob/master/src/templates/_base.html#L14-L15 and here
https://github.com/wolframkriesing/site-stitcher/blob/master/src/templates/_base.html#L19-L20
notice the extra newline, which is not really needed other than preventing tundra from throwing the above mentioned error.
And the child using it is not anything special 
https://github.com/wolframkriesing/site-stitcher/blob/master/src/templates/index.html#L3-L5

**Comment by Usbac** [comment]
Hello @wolframkriesing! Thank you for giving me the code snippet.

It has been fixed :)
 1c97c00e56242122a90079ce59560da32f8db6b4

The solution comes in the version 1.1.1.
