### ISSUE TITLE
@extends does not respect the baseDir

### ISSUE THREAD

**Issue by wolframkriesing** [Usbac/tundra#5]
In the `@extends(src/templates/_base.html)` I always have to pass the `src/templates` too, even though I have set it via `tundra.setBase('src/templates')`.
Is this intended or a bug?

**Comment by Usbac** [comment]
Hello @wolframkriesing! Yes it is intended, but that will change for the next major release soon. :)

**Comment by wolframkriesing** [comment]
thanks, looking fwd to it
